---
- name: SIP Install Packages
  hosts: localhost
  become: true
  tasks:
    - name: Install prerequisites
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - haproxy
        - httpd
        - targetcli
        - nfs-utils
        - nfs4-acl-tools
        - chrony
        - samba
        - httpd
        - mod_ssl
        - realmd
        - sssd
        - oddjob
        - oddjob-mkhomedir
        - adcli
        - samba-common-tools
