---
- name: SIP NTP
  hosts: localhost
  become: true
  tasks:
    - name: Install chrony if not present
      ansible.builtin.yum:
        name: chrony
        state: present

    - name: Modify chrony.conf
      ansible.builtin.lineinfile:
        path: /etc/chrony.conf
        line: "{{ item }}"
        state: present
      loop:
        - "allow 192.168.1.0/24"
        - "server 1.hr.pool.ntp.org iburst"

    - name: Allow NTP through Firewall
      ansible.builtin.firewalld:
        service: ntp
        permanent: true
        state: enabled

    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

